[package]
name = "interretialem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "interretialem"

[dependencies]
binrw = "0.13.3"
leb128 = "0.2.5"
